<?xml version="1.0"?>

<robot name="base" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define a number of dimensions using properties -->
  <!-- set the mobile base physical parameter -->
  <property name="mass" value="1" />
  <property name="wheel_mass" value="0.2" />
  <property name="base_size_x" value="0.30" />
  <property name="base_size_y" value="0.30" />
  <property name="base_size_z" value="0.12" />
  <property name="wheel_length" value="0.02032" />
  <property name="wheel_radius" value="0.06191" />
  <property name="wheel_offset_x" value="0.09" />
  <property name="wheel_offset_y" value="0.17" />
  <property name="wheel_offset_z" value="-0.038" />
  
  <property name="PI" value="3.1415" />
  


  <!-- define a wheel -->
  <macro name="wheel" params="suffix parent reflect color">
    <joint name="${parent}_${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 0 1" />
      <limit effort="100" velocity="100"/>
      <safety_controller k_velocity="10" />
      <origin xyz="${wheel_offset_x} ${reflect*wheel_offset_y} ${wheel_offset_z}" rpy="${-PI/2} 0 0" />
      <parent link="${parent}_link"/>
      <child link="${parent}_${suffix}_wheel_link"/>
    </joint>
    <link name="${parent}_${suffix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="${color}" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="${color}" />
      </collision>
      <!-- just give random value-->
      <inertial>
      <mass value="${wheel_mass}" />
      <inertia ixx="${2.0 / 5.0 * wheel_mass * wheel_radius * wheel_radius}" ixy="0.0" ixz="0.0"
               iyy="${2.0 / 5.0 * wheel_mass * wheel_radius * wheel_radius}" iyz="0.0"
               izz="${2.0 / 5.0 * wheel_mass * wheel_radius * wheel_radius}" />
    </inertial>
    </link>
  </macro>

  <!-- The base xacro macro -->
  <macro name="base" params="name color">
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
        </geometry>
        <material name="${color}" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${base_size_x} ${wheel_offset_y*2 + wheel_length} ${base_size_z}" />
        </geometry>
      </collision>
      <inertial>
      <origin xyz="0 0 ${base_size_z/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (base_size_y*base_size_y + base_size_z*base_size_z)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (base_size_z*base_size_z + base_size_x*base_size_x)}" iyz="0.0"
	  izz="${mass / 12.0 * (base_size_x*base_size_x + base_size_y*base_size_y)}"/>
      </inertial>
    </link>
  </macro>
  


<!-- robot cycle center sometimes is not the robot center, specify it -->
  <link name="base_footprint">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <sphere radius="0.01"/>
        </geometry>
        <material name="TransparentGreen" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <sphere radius="0.01"/>
        </geometry>
        <material name="TransparentGreen" />
      </collision>
        <inertial>
	<mass value="0.01"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
	<inertia
	  ixx="0.001" ixy="0.0" ixz="0.0"
	  iyy="0.001" iyz="0.0"
	  izz="0.001"/>
      </inertial>

  </link>
  
  <joint name="base_joint" type="fixed">
    <origin xyz="0 0 ${base_size_z/2 - wheel_offset_z - 0.01} " rpy="0 0 0" />        
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

   <!-- Add the drive wheels -->
   <wheel parent="base" suffix="l" reflect="1" color="Orange"/>
   <wheel parent="base" suffix="r" reflect="-1" color="Orange"/>

  <xacro:include filename="$(find spark_urdf)/urdf/base.gazebo" />

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_l_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_r_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>-1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
